services:
  postgres:
    image: postgres:16-alpine
    container_name: pocketbook-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: pocketbook
      POSTGRES_PASSWORD: pocketbook_dev_password
      POSTGRES_DB: pocketbook
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pocketbook-redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
